
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 4;
  public static final int FROM = 3;
  public static final int AND = 5;
  public static final int LT = 9;
  public static final int SEMICOLON = 14;
  public static final int SELECT = 2;
  public static final int OR = 6;
  public static final int STAR = 15;
  public static final int GT = 11;
  public static final int ID = 16;
  public static final int LE = 10;
  public static final int STRING = 17;
  public static final int COMMA = 13;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int GE = 12;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int NEQ = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "OR",
  "EQ",
  "NEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "COMMA",
  "SEMICOLON",
  "STAR",
  "ID",
  "STRING",
  "NUMBER"
  };
}

